### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by wuzhongyi1105** [dragonfly-club/mastodon-translators-api#2]
I attempted to build the image, but it kept failing. The failure logs are as follows:

```
[thread 0][gcc] core/legion.o
52.52       core/ssl.c: In function ‘uwsgi_ssl_new_server_context’:
52.52       core/ssl.c:268:17: warning: ‘PEM_read_bio_DHparams’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         268 |                 DH *dh = PEM_read_bio_DHparams(bio, NULL, NULL, NULL);
52.52             |                 ^~
52.52       In file included from /usr/include/openssl/ssl.h:36,
52.52                        from ./uwsgi.h:357,
52.52                        from core/ssl.c:1:
52.52       /usr/include/openssl/pem.h:469:1: note: declared here
52.52         469 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, DHparams, DH)
52.52             | ^~~~~~~~~~~~~~~~~~~
52.52       core/ssl.c:273:25: warning: ‘DH_free’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         273 |                         DH_free(dh);
52.52             |                         ^~~~~~~
52.52       In file included from /usr/include/openssl/dsa.h:51,
52.52                        from /usr/include/openssl/x509.h:37,
52.52                        from /usr/include/openssl/ssl.h:31:
52.52       /usr/include/openssl/dh.h:204:28: note: declared here
52.52         204 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
52.52             |                            ^~~~~~~
52.52       core/ssl.c:279:9: warning: ‘EC_KEY_new_by_curve_name’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         279 |         EC_KEY *ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
52.52             |         ^~~~~~
52.52       In file included from /usr/include/openssl/x509.h:33:
52.52       /usr/include/openssl/ec.h:998:31: note: declared here
52.52         998 | OSSL_DEPRECATEDIN_3_0 EC_KEY *EC_KEY_new_by_curve_name(int nid);
52.52             |                               ^~~~~~~~~~~~~~~~~~~~~~~~
52.52       core/ssl.c:283:17: warning: ‘EC_KEY_free’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         283 |                 EC_KEY_free(ecdh);
52.52             |                 ^~~~~~~~~~~
52.52       /usr/include/openssl/ec.h:1003:28: note: declared here
52.52        1003 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
52.52             |                            ^~~~~~~~~~~
52.52       core/ssl.c: In function ‘uwsgi_sha1’:
52.52       core/ssl.c:563:9: warning: ‘SHA1_Init’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         563 |         SHA1_Init(&sha);
52.52             |         ^~~~~~~~~
52.52       In file included from /usr/include/openssl/x509.h:41:
52.52       /usr/include/openssl/sha.h:49:27: note: declared here
52.52          49 | OSSL_DEPRECATEDIN_3_0 int SHA1_Init(SHA_CTX *c);
52.52             |                           ^~~~~~~~~
52.52       core/ssl.c:564:9: warning: ‘SHA1_Update’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         564 |         SHA1_Update(&sha, src, len);
52.52             |         ^~~~~~~~~~~
52.52       /usr/include/openssl/sha.h:50:27: note: declared here
52.52          50 | OSSL_DEPRECATEDIN_3_0 int SHA1_Update(SHA_CTX *c, const void *data, size_t len);
52.52             |                           ^~~~~~~~~~~
52.52       core/ssl.c:565:9: warning: ‘SHA1_Final’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         565 |         SHA1_Final((unsigned char *)dst, &sha);
52.52             |         ^~~~~~~~~~
52.52       /usr/include/openssl/sha.h:51:27: note: declared here
52.52          51 | OSSL_DEPRECATEDIN_3_0 int SHA1_Final(unsigned char *md, SHA_CTX *c);
52.52             |                           ^~~~~~~~~~
52.52       core/ssl.c: In function ‘uwsgi_md5’:
52.52       core/ssl.c:571:9: warning: ‘MD5_Init’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         571 |         MD5_Init(&md5);
52.52             |         ^~~~~~~~
52.52       In file included from core/ssl.c:4:
52.52       /usr/include/openssl/md5.h:49:27: note: declared here
52.52          49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
52.52             |                           ^~~~~~~~
52.52       core/ssl.c:572:9: warning: ‘MD5_Update’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         572 |         MD5_Update(&md5, src, len);
52.52             |         ^~~~~~~~~~
52.52       /usr/include/openssl/md5.h:50:27: note: declared here
52.52          50 | OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
52.52             |                           ^~~~~~~~~~
52.52       core/ssl.c:573:9: warning: ‘MD5_Final’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         573 |         MD5_Final((unsigned char *)dst, &md5);
52.52             |         ^~~~~~~~~
52.52       /usr/include/openssl/md5.h:51:27: note: declared here
52.52          51 | OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
52.52             |                           ^~~~~~~~~
52.52       core/ssl.c: In function ‘uwsgi_sha1_2n’:
52.52       core/ssl.c:579:9: warning: ‘SHA1_Init’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         579 |         SHA1_Init(&sha);
52.52             |         ^~~~~~~~~
52.52       /usr/include/openssl/sha.h:49:27: note: declared here
52.52          49 | OSSL_DEPRECATEDIN_3_0 int SHA1_Init(SHA_CTX *c);
52.52             |                           ^~~~~~~~~
52.52       core/ssl.c:580:9: warning: ‘SHA1_Update’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         580 |         SHA1_Update(&sha, s1, len1);
52.52             |         ^~~~~~~~~~~
52.52       /usr/include/openssl/sha.h:50:27: note: declared here
52.52          50 | OSSL_DEPRECATEDIN_3_0 int SHA1_Update(SHA_CTX *c, const void *data, size_t len);
52.52             |                           ^~~~~~~~~~~
52.52       core/ssl.c:581:9: warning: ‘SHA1_Update’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         581 |         SHA1_Update(&sha, s2, len2);
52.52             |         ^~~~~~~~~~~
52.52       /usr/include/openssl/sha.h:50:27: note: declared here
52.52          50 | OSSL_DEPRECATEDIN_3_0 int SHA1_Update(SHA_CTX *c, const void *data, size_t len);
52.52             |                           ^~~~~~~~~~~
52.52       core/ssl.c:582:9: warning: ‘SHA1_Final’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
52.52         582 |         SHA1_Final((unsigned char *)dst, &sha);
52.52             |         ^~~~~~~~~~
52.52       /usr/include/openssl/sha.h:51:27: note: declared here
52.52          51 | OSSL_DEPRECATEDIN_3_0 int SHA1_Final(unsigned char *md, SHA_CTX *c);
52.52             |                           ^~~~~~~~~~
52.52       [thread 1][gcc] core/xmlconf.o
52.52       [thread 0][gcc] core/dot_h.o
52.52       [thread 0][gcc] core/config_py.o
52.52       *** uWSGI compiling embedded plugins ***
52.52       [thread 0][gcc] plugins/python/python_plugin.o
52.52       [thread 1][gcc] plugins/python/pyutils.o
52.52       plugins/python/python_plugin.c:138:9: warning: ‘Py_NoSiteFlag’ is deprecated [-Wdeprecated-declarations]
52.52         138 |         {"no-site", no_argument, 0, "do not import site module", uwsgi_opt_true, &Py_NoSiteFlag, 0},
52.52             |         ^
52.52       In file included from /usr/local/include/python3.12/Python.h:48,
52.52                        from plugins/python/uwsgi_python.h:4,
52.52                        from plugins/python/python_plugin.c:1:
52.52       /usr/local/include/python3.12/cpython/pydebug.h:14:37: note: declared here
52.52          14 | Py_DEPRECATED(3.12) PyAPI_DATA(int) Py_NoSiteFlag;
52.52             |                                     ^~~~~~~~~~~~~
52.52       plugins/python/pyutils.c: In function ‘init_pyargv’:
52.52       plugins/python/pyutils.c:391:9: warning: ‘PySys_SetArgv’ is deprecated [-Wdeprecated-declarations]
52.52         391 |         PySys_SetArgv(up.argc, up.py_argv);
52.52             |         ^~~~~~~~~~~~~
52.52       In file included from /usr/local/include/python3.12/Python.h:96,
52.52                        from plugins/python/uwsgi_python.h:4,
52.52                        from plugins/python/pyutils.c:1:
52.52       /usr/local/include/python3.12/sysmodule.h:13:38: note: declared here
52.52          13 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) PySys_SetArgv(int, wchar_t **);
52.52             |                                      ^~~~~~~~~~~~~
52.52       plugins/python/python_plugin.c: In function ‘uwsgi_python_init’:
52.52       plugins/python/python_plugin.c:239:17: warning: ‘Py_SetPythonHome’ is deprecated [-Wdeprecated-declarations]
52.52         239 |                 Py_SetPythonHome(wpyhome);
52.52             |                 ^~~~~~~~~~~~~~~~
52.52       In file included from /usr/local/include/python3.12/Python.h:94:
52.52       /usr/local/include/python3.12/pylifecycle.h:40:38: note: declared here
52.52          40 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) Py_SetPythonHome(const wchar_t *);
52.52             |                                      ^~~~~~~~~~~~~~~~
52.52       plugins/python/python_plugin.c:263:9: warning: ‘Py_SetProgramName’ is deprecated [-Wdeprecated-declarations]
52.52         263 |         Py_SetProgramName(pname);
52.52             |         ^~~~~~~~~~~~~~~~~
52.52       /usr/local/include/python3.12/pylifecycle.h:37:38: note: declared here
52.52          37 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) Py_SetProgramName(const wchar_t *);
52.52             |                                      ^~~~~~~~~~~~~~~~~
52.52       plugins/python/python_plugin.c:269:9: warning: ‘Py_OptimizeFlag’ is deprecated [-Wdeprecated-declarations]
52.52         269 |         Py_OptimizeFlag = up.optimize;
52.52             |         ^~~~~~~~~~~~~~~
52.52       /usr/local/include/python3.12/cpython/pydebug.h:13:37: note: declared here
52.52          13 | Py_DEPRECATED(3.12) PyAPI_DATA(int) Py_OptimizeFlag;
52.52             |                                     ^~~~~~~~~~~~~~~
52.52       plugins/python/python_plugin.c: In function ‘uwsgi_python_pre_uwsgi_fork’:
52.52       plugins/python/python_plugin.c:1327:17: error: too few arguments to function ‘_PyImport_AcquireLock’
52.52        1327 |                 _PyImport_AcquireLock();
52.52             |                 ^~~~~~~~~~~~~~~~~~~~~
52.52       In file included from /usr/local/include/python3.12/import.h:91,
52.52                        from /usr/local/include/python3.12/Python.h:99:
52.52       /usr/local/include/python3.12/cpython/import.h:13:18: note: declared here
52.52          13 | PyAPI_FUNC(void) _PyImport_AcquireLock(PyInterpreterState *interp);
52.52             |                  ^~~~~~~~~~~~~~~~~~~~~
52.52       plugins/python/python_plugin.c: In function ‘uwsgi_python_post_uwsgi_fork’:
52.52       plugins/python/python_plugin.c:1339:25: error: too few arguments to function ‘_PyImport_ReleaseLock’
52.52        1339 |                         _PyImport_ReleaseLock();
52.52             |                         ^~~~~~~~~~~~~~~~~~~~~
52.52       /usr/local/include/python3.12/cpython/import.h:14:17: note: declared here
52.52          14 | PyAPI_FUNC(int) _PyImport_ReleaseLock(PyInterpreterState *interp);
52.52             |                 ^~~~~~~~~~~~~~~~~~~~~
52.52       plugins/python/python_plugin.c: In function ‘uwsgi_python_suspend’:
52.52       plugins/python/python_plugin.c:1596:78: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘recursion_remaining’; did you mean ‘c_recursion_remaining’?
52.52        1596 |                 up.current_recursion_remaining[wsgi_req->async_id] = tstate->recursion_remaining;
52.52             |                                                                              ^~~~~~~~~~~~~~~~~~~
52.52             |                                                                              c_recursion_remaining
52.52       plugins/python/python_plugin.c:1605:63: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘recursion_remaining’; did you mean ‘c_recursion_remaining’?
52.52        1605 |                 up.current_main_recursion_remaining = tstate->recursion_remaining;
52.52             |                                                               ^~~~~~~~~~~~~~~~~~~
52.52             |                                                               c_recursion_remaining
52.52       plugins/python/python_plugin.c: In function ‘uwsgi_python_resume’:
52.52       plugins/python/python_plugin.c:1839:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘recursion_remaining’; did you mean ‘c_recursion_remaining’?
52.52        1839 |                 tstate->recursion_remaining = up.current_recursion_remaining[wsgi_req->async_id];
52.52             |                         ^~~~~~~~~~~~~~~~~~~
52.52             |                         c_recursion_remaining
52.52       plugins/python/python_plugin.c:1848:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘recursion_remaining’; did you mean ‘c_recursion_remaining’?
52.52        1848 |                 tstate->recursion_remaining = up.current_main_recursion_remaining;
52.52             |                         ^~~~~~~~~~~~~~~~~~~
52.52             |                         c_recursion_remaining
52.52       [end of output]
52.52   
52.52   note: This error originates from a subprocess, and is likely not a problem with pip.
52.52   ERROR: Failed building wheel for uWSGI
52.53   Running setup.py clean for uWSGI
52.85   Building wheel for fasttext-langdetect (setup.py): started
53.28   Building wheel for fasttext-langdetect (setup.py): finished with status 'done'
53.28   Created wheel for fasttext-langdetect: filename=fasttext_langdetect-1.0.5-py3-none-any.whl size=7503 sha256=b094231589870bc7da363efc1aa7ee74b594414e006d5ff3a0cb6130ad9205d6
53.28   Stored in directory: /root/.cache/pip/wheels/02/98/3e/91a2527cd5ff03e889b6089faf95681f8cc6310eb72a0c636a
53.29   Building wheel for fasttext (setup.py): started
114.9   Building wheel for fasttext (setup.py): still running...
141.5   Building wheel for fasttext (setup.py): finished with status 'done'
141.5   Created wheel for fasttext: filename=fasttext-0.9.2-cp312-cp312-linux_x86_64.whl size=4556450 sha256=9ff0a6c09e69613734bfdc0eee2d9f66c3f89c55a642bd716df2dd2aaa0b2234
141.5   Stored in directory: /root/.cache/pip/wheels/3f/14/26/663abec04e7eb8ce47b13edeec3b19ad0435cf6366e27a2635
141.6   Building wheel for PyExecJS (setup.py): started
142.0   Building wheel for PyExecJS (setup.py): finished with status 'done'
142.0   Created wheel for PyExecJS: filename=PyExecJS-1.5.1-py3-none-any.whl size=14578 sha256=0effa03308ff70611e89b41dd1c03a31d39cce9b23c7fbe8c7c16a042f36c52b
142.0   Stored in directory: /root/.cache/pip/wheels/95/1c/16/774a935204aacf741cea3deae76c535050d19727c72613d80f
142.0 Successfully built fasttext-langdetect fasttext PyExecJS
142.0 Failed to build uWSGI
142.0 ERROR: Could not build wheels for uWSGI, which is required to install pyproject.toml-based projects
142.1 
```

So, I tried using the 3.9 image, and the build was successful. Moreover, the translation from Chinese to English worked very well. However, I'm unable to set the target language to any other language.

The error logs are as follows.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./app.py", line 87, in translate
    _results['translatedText'].append(_result['translatedText'])
TypeError: tuple indices must be integers or slices, not str
[pid: 20|app: 0|req: 2/2] 172.17.0.1 () {34 vars in 389 bytes} [Sun Oct 22 03:42:25 2023] POST /translate => generated 265 bytes in 5 msecs (HTTP/1.0 500) 2 headers in 99 bytes (1 switches on core 0)
[pid: 22|app: 0|req: 1/3] 172.17.0.1 () {34 vars in 389 bytes} [Sun Oct 22 03:42:33 2023] POST /translate => generated 143 bytes in 12 msecs (HTTP/1.0 200) 2 headers in 72 bytes (1 switches on core 0)
[2023-10-22 03:43:03,215] ERROR in app: Exception on /translate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./app.py", line 87, in translate
    _results['translatedText'].append(_result['translatedText'])
TypeError: tuple indices must be integers or slices, not str
[pid: 20|app: 0|req: 3/4] 172.17.0.1 () {34 vars in 389 bytes} [Sun Oct 22 03:43:03 2023] POST /translate => generated 265 bytes in 2 msecs (HTTP/1.0 500) 2 headers in 99 bytes (1 switches on core 0)
[2023-10-22 03:58:31,222] ERROR in app: Exception on /translate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./app.py", line 87, in translate
    _results['translatedText'].append(_result['translatedText'])
TypeError: tuple indices must be integers or slices, not str
[pid: 19|app: 0|req: 1/5] 172.17.0.1 () {34 vars in 389 bytes} [Sun Oct 22 03:58:31 2023] POST /translate => generated 265 bytes in 82 msecs (HTTP/1.0 500) 2 headers in 99 bytes (1 switches on core 0)
```

**Comment by HolgerHuo** [comment]
> I attempted to build the image, but it kept failing.

https://github.com/unbit/uwsgi/issues/2566 The issue originates from uWSGI. This project now builds its container image with Python v3.11. https://github.com/dragonfly-club/mastodon-translators-api/commit/bed8202421d5e11e2d7cbfc77f63dabc4193a488

> However, I'm unable to set the target language to any other language.

Due to Island 岛屿 maintainers use English as the interface language, we did not uncover this issue in advance. Sorry for this problem. The issue exists because we didn't accept zh-CN, zh-HK, and zh-TW as valid target languages but only `zh`, and some of the language codes (ja, ko) were misspelled. This has been fixed in https://github.com/dragonfly-club/mastodon-translators-api/releases/tag/v1.3.2

In addition, now we provide an official docker build at https://hub.docker.com/r/dragonflyclub/mastodon-translators-api for easy deployment.
